Repository XanaduAI/MrMustard, pull requests merged in 2022-09, with the labels that each got.

#156 bugfix - hermitian conjugate 🐛
  .github/CHANGELOG.md
  mrmustard/math/math_interface.py
  tests/test_lab/test_gates_fock.py
Labels: bug

#140 Iterable states
  .github/CHANGELOG.md
  mrmustard/lab/abstract/state.py
  tests/test_lab/test_states.py
Labels: enhancement

#157 Tidy up CHANGELOG
  .github/CHANGELOG.md
Labels: documentation
