Repository XanaduAI/MrMustard, pull requests merged in 2024-12, with the labels that each got.

#520 Adding a bunch of gates from the lab
  .pylintrc
  mrmustard/lab_dev/states/__init__.py
  mrmustard/lab_dev/states/bargmann_eigenstate.py
  mrmustard/lab_dev/states/gstate.py
  mrmustard/lab_dev/states/ket.py
  mrmustard/lab_dev/transformations/__init__.py
  mrmustard/lab_dev/transformations/cxgate.py
  mrmustard/lab_dev/transformations/czgate.py
  mrmustard/lab_dev/transformations/ggate.py
  mrmustard/lab_dev/transformations/interferometer.py
  mrmustard/lab_dev/transformations/mzgate.py
  mrmustard/lab_dev/transformations/pgate.py
  mrmustard/lab_dev/transformations/phasenoise.py
  mrmustard/lab_dev/transformations/realinterferometer.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/physics/bargmann_utils.py
  mrmustard/physics/gaussian_integrals.py
  mrmustard/physics/triples.py
  tests/test_lab_dev/test_states/test_bargmann_eigenstate.py
  tests/test_lab_dev/test_states/test_gstate.py
  tests/test_lab_dev/test_transformations/test_cft.py
  tests/test_lab_dev/test_transformations/test_cxgate.py
  tests/test_lab_dev/test_transformations/test_czgate.py
  tests/test_lab_dev/test_transformations/test_interferometer.py
  tests/test_lab_dev/test_transformations/test_mzgate.py
  tests/test_lab_dev/test_transformations/test_pgate.py
  tests/test_lab_dev/test_transformations/test_phasenoise.py
  tests/test_lab_dev/test_transformations/test_realinterferometer.py
Labels: no changelog

#531 fix the ipython_display side effect
  .github/CHANGELOG.md
  .github/workflows/tests_numpy.yml
  .github/workflows/tests_tensorflow.yml
  mrmustard/lab_dev/circuit_components.py
  mrmustard/lab_dev/states/dm.py
  mrmustard/lab_dev/states/ket.py
  mrmustard/physics/ansatz/array_ansatz.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
  mrmustard/physics/wires.py
  mrmustard/widgets/__init__.py
  tests/test_lab_dev/test_circuit_components.py
  tests/test_physics/test_ansatz/test_array_ansatz.py
  tests/test_physics/test_ansatz/test_polyexp_ansatz.py
  tests/test_physics/test_wires.py
Labels: enhancement, Review effort [1-5]: 2, tests

#528 Python 3.12 version bump
  .github/workflows/tests_numpy.yml
  .github/workflows/tests_tensorflow.yml
  .gitignore
  mrmustard/math/backend_tensorflow.py
  mrmustard/physics/triples.py
  mrmustard/training/optimizer.py
  poetry.lock
  pyproject.toml
  tests/test_math/test_backend_manager.py
  tests/test_math/test_tensor_networks/test_tensors.py
  tests/test_training/test_opt.py
Labels: enhancement, dependencies, no changelog, Review effort [1-5]: 2

#530 Unitary/Channel from fock
  mrmustard/lab_dev/transformations/base.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
  tests/test_lab_dev/test_transformations/test_transformations_base.py
Labels: no changelog
