Repository XanaduAI/MrMustard, pull requests merged in 2025-04, with the labels that each got.

#568 allow backend hot-swap
  mrmustard/math/backend_manager.py
Labels: enhancement, no changelog, Review effort 2/5

#563 Batching triples.py and symplectics.py
  mrmustard/lab_dev/circuit_components_utils/b_to_q.py
  mrmustard/lab_dev/states/bargmann_eigenstate.py
  mrmustard/lab_dev/states/base.py
  mrmustard/lab_dev/states/quadrature_eigenstate.py
  mrmustard/lab_dev/states/squeezed_vacuum.py
  mrmustard/lab_dev/transformations/s2gate.py
  mrmustard/lab_dev/transformations/sgate.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/physics/symplectics.py
  mrmustard/physics/triples.py
  tests/test_physics/test_gaussian_integrals.py
  tests/test_physics/test_triples.py
Labels: no changelog

#575 adds atol to allclose in ansatz
  mrmustard/physics/ansatz/array_ansatz.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
Labels: no changelog

#574 Tidy up hermite_renormalized and add missing gradients
  mrmustard/lab_dev/states/dm.py
  mrmustard/lab_dev/states/ket.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/math/lattice/autoshape.py
  mrmustard/math/lattice/strategies/fast_diagonal.py
  mrmustard/math/lattice/strategies/vanilla.py
  mrmustard/math/lattice/strategies/vanilla/__init__.py
  mrmustard/math/lattice/strategies/vanilla/batch.py
  mrmustard/math/lattice/strategies/vanilla/core.py
  mrmustard/math/lattice/strategies/vanilla/gradients.py
  mrmustard/utils/settings.py
  tests/test_math/test_fast_diagonal.py
  tests/test_math/test_lattice.py
  tests/test_math/test_vanilla.py
Labels: enhancement, no changelog, tests, Review effort 3/5

#577 Fix visualize_2d
  mrmustard/lab_dev/states/base.py
  tests/test_lab_dev/assets/visualize_2d.json
Labels: no changelog, Bug fix

#576 Updated API of contract for Ansatze
  mrmustard/lab_dev/circuit_components_utils/trace_out.py
  mrmustard/lab_dev/transformations/base.py
  mrmustard/physics/ansatz/array_ansatz.py
  mrmustard/physics/ansatz/base.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
  mrmustard/physics/gaussian_integrals.py
  mrmustard/physics/representations.py
  mrmustard/physics/utils.py
  mrmustard/physics/wires.py
  tests/test_lab_dev/test_circuit_components_utils/test_trace_out.py
  tests/test_lab_dev/test_transformations/test_transformations_base.py
  tests/test_physics/test_ansatz/test_array_ansatz.py
  tests/test_physics/test_ansatz/test_polyexp_ansatz.py
  tests/test_physics/test_representations.py
  tests/test_physics/test_triples.py
  tests/test_physics/test_wires.py
Labels: no changelog

#582 removes spaces from einsum string
  mrmustard/lab_dev/states/dm.py
  mrmustard/lab_dev/states/ket.py
  tests/test_lab_dev/test_circuit_components_utils/test_b_to_ps.py
  tests/test_lab_dev/test_states/test_dm.py
Labels: no changelog

#551 initial docstring improvement
  mrmustard/lab_dev/circuit_components.py
  mrmustard/lab_dev/circuit_components_utils/b_to_ch.py
  mrmustard/lab_dev/circuit_components_utils/b_to_q.py
  mrmustard/lab_dev/circuit_components_utils/trace_out.py
  mrmustard/lab_dev/states/bargmann_eigenstate.py
  mrmustard/lab_dev/states/base.py
  mrmustard/lab_dev/states/coherent.py
  mrmustard/lab_dev/states/displaced_squeezed.py
  mrmustard/lab_dev/states/dm.py
  mrmustard/lab_dev/states/gaussian_state.py
  mrmustard/lab_dev/states/ket.py
  mrmustard/lab_dev/states/number.py
  mrmustard/lab_dev/states/quadrature_eigenstate.py
  mrmustard/lab_dev/states/sauron.py
  mrmustard/lab_dev/states/squeezed_vacuum.py
  mrmustard/lab_dev/states/thermal.py
  mrmustard/lab_dev/states/two_mode_squeezed_vacuum.py
  mrmustard/lab_dev/states/vacuum.py
  mrmustard/lab_dev/transformations/amplifier.py
  mrmustard/lab_dev/transformations/attenuator.py
  mrmustard/lab_dev/transformations/base.py
  mrmustard/lab_dev/transformations/bsgate.py
  mrmustard/lab_dev/transformations/cxgate.py
  mrmustard/lab_dev/transformations/czgate.py
  mrmustard/lab_dev/transformations/dgate.py
  mrmustard/lab_dev/transformations/fockdamping.py
  mrmustard/lab_dev/transformations/gaussrandnoise.py
  mrmustard/lab_dev/transformations/ggate.py
  mrmustard/lab_dev/transformations/identity.py
  mrmustard/lab_dev/transformations/interferometer.py
  mrmustard/lab_dev/transformations/mzgate.py
  mrmustard/lab_dev/transformations/pgate.py
  mrmustard/lab_dev/transformations/phasenoise.py
  mrmustard/lab_dev/transformations/realinterferometer.py
  mrmustard/lab_dev/transformations/rgate.py
  mrmustard/lab_dev/transformations/s2gate.py
  mrmustard/lab_dev/transformations/sgate.py
  mrmustard/physics/triples.py
Labels: documentation, enhancement, no changelog, Review effort 2/5
