Repository XanaduAI/MrMustard, pull requests merged in 2025-02, with the labels that each got.

#549 Fixing Mr Mustard's build
  .github/workflows/format.yml
  .pre-commit-config.yaml
  mrmustard/lab/abstract/measurement.py
  mrmustard/lab/gates.py
  mrmustard/math/lattice/strategies/compactFock/diagonal_grad.py
  mrmustard/training/callbacks.py
  mrmustard/utils/typing.py
  pyproject.toml
  uv.lock
Labels: no changelog

#552 Finalize switch from poetry to uv
  .dockerignore
  .readthedocs.yml
  doc/code/utils/settings.rst
  env.Dockerfile
  mrmustard/utils/settings.py
  pyproject.toml
  uv.lock
Labels: enhancement, no changelog, Review effort [1-5]: 2, configuration changes

#554 Switching Mr Mustard to numpy 2.0+
  mrmustard/math/backend_numpy.py
  pyproject.toml
  uv.lock
Labels: no changelog

#553 Increment version to 1.0.0-dev
  .github/CHANGELOG.md
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 1

#555 Add the uv pre-commit hook
  .pre-commit-config.yaml
  uv.lock
Labels: enhancement, no changelog, configuration changes, Review effort 1/5

#556 atleast_nd
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  tests/test_math/test_backend_manager.py
Labels: no changelog

#546 Adding a Jax backend
  .github/workflows/tests_jax.yml
  mrmustard/lab/abstract/state.py
  mrmustard/lab/states.py
  mrmustard/lab_dev/circuit_components.py
  mrmustard/lab_dev/samplers.py
  mrmustard/lab_dev/states/ket.py
  mrmustard/lab_dev/transformations/gaussrandnoise.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/math/parameter_set.py
  mrmustard/math/tensor_wrappers/xptensor.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
  mrmustard/physics/bargmann_utils.py
  mrmustard/physics/fock_utils.py
  mrmustard/physics/gaussian.py
  mrmustard/physics/gaussian_integrals.py
  mrmustard/physics/representations.py
  mrmustard/physics/triples.py
  pyproject.toml
  tests/conftest.py
  tests/test_lab/test_detectors.py
  tests/test_lab/test_gates_fock.py
  tests/test_lab_dev/test_circuit_components.py
  tests/test_lab_dev/test_samplers.py
  tests/test_lab_dev/test_states/test_bargmann_eigenstate.py
  tests/test_lab_dev/test_states/test_dm.py
  tests/test_lab_dev/test_states/test_states_visualization.py
  tests/test_lab_dev/test_transformations/test_transformations_base.py
  tests/test_math/test_backend_manager.py
  tests/test_math/test_compactFock.py
  tests/test_math/test_jitting.py
  tests/test_math/test_lattice.py
  tests/test_math/test_tensor_networks/test_integration.py
  tests/test_physics/test_triples.py
  tests/test_physics/test_wires.py
  tests/test_training/test_callbacks.py
  tests/test_training/test_opt_lab.py
  tests/test_training/test_opt_lab_dev.py
  tests/test_training/test_riemannian_opt.py
  tests/test_training/test_trainer.py
  tests/test_utils/test_serialize.py
  tests/test_utils/test_settings.py
  uv.lock
Labels: enhancement, no changelog, Review effort [1-5]: 4, tests

#562 Restrict to Python 3.10+
  pyproject.toml
  uv.lock
Labels: no changelog
