Repository XanaduAI/MrMustard, pull requests merged in 2025-07, with the labels that each got.

#613 improved c of inverse
  mrmustard/lab/circuit_components_utils/b_to_q.py
  mrmustard/lab/transformations/base.py
Labels: no changelog

#620 Updating CODEOWNERS
  .github/CODEOWNERS
Labels: no changelog, Review effort 1/5, Other

#614 Adding a setting to switch the default contraction representation
  mrmustard/lab/circuit_components.py
  mrmustard/utils/settings.py
  tests/test_lab/test_circuit_components.py
  tests/test_utils/test_settings.py
Labels: no changelog

#628 [Sc 95331] Batched Number
  mrmustard/lab/states/number.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/physics/fock_utils.py
  tests/test_lab/test_circuits.py
  tests/test_lab/test_states/test_number.py
  tests/test_math/test_backend_manager.py
  tests/test_physics/test_fock_utils.py
Labels: enhancement, no changelog, Review effort 4/5

#626 [sc-95329] Adding dtype to make parameter on built-ins and improving mode argument
  mrmustard/lab/circuit_components.py
  mrmustard/lab/states/bargmann_eigenstate.py
  mrmustard/lab/states/coherent.py
  mrmustard/lab/states/displaced_squeezed.py
  mrmustard/lab/states/gaussian_state.py
  mrmustard/lab/states/number.py
  mrmustard/lab/states/quadrature_eigenstate.py
  mrmustard/lab/states/sauron.py
  mrmustard/lab/states/squeezed_vacuum.py
  mrmustard/lab/states/thermal.py
  mrmustard/lab/states/two_mode_squeezed_vacuum.py
  mrmustard/lab/transformations/amplifier.py
  mrmustard/lab/transformations/attenuator.py
  mrmustard/lab/transformations/bsgate.py
  mrmustard/lab/transformations/cxgate.py
  mrmustard/lab/transformations/czgate.py
  mrmustard/lab/transformations/dgate.py
  mrmustard/lab/transformations/fockdamping.py
  mrmustard/lab/transformations/mzgate.py
  mrmustard/lab/transformations/pgate.py
  mrmustard/lab/transformations/phasenoise.py
  mrmustard/lab/transformations/rgate.py
  mrmustard/lab/transformations/s2gate.py
  mrmustard/lab/transformations/sgate.py
  tests/test_physics/test_symplectics.py
Labels: enhancement, no changelog, Review effort 3/5

#618 Adding Fock shape information to the Wires + Fock shape lookahead
  mrmustard/lab/circuit_components.py
  mrmustard/lab/circuit_components_utils/b_to_ch.py
  mrmustard/lab/circuit_components_utils/b_to_ps.py
  mrmustard/lab/circuit_components_utils/b_to_q.py
  mrmustard/lab/states/dm.py
  mrmustard/lab/states/ket.py
  mrmustard/lab/states/number.py
  mrmustard/lab/states/quadrature_eigenstate.py
  mrmustard/lab/states/vacuum.py
  mrmustard/lab/transformations/bsgate.py
  mrmustard/lab/transformations/dgate.py
  mrmustard/physics/wires.py
  tests/test_lab/test_circuit_components.py
  tests/test_lab/test_states/test_dm.py
  tests/test_lab/test_states/test_ket.py
  tests/test_lab/test_states/test_number.py
  tests/test_lab/test_states/test_states_visualization.py
  tests/test_physics/test_wires.py
Labels: enhancement, no changelog, Review effort 4/5

#630 Adding a comment to binomial_subspace_basis for numba caching issues
  mrmustard/math/lattice/paths.py
Labels: documentation, no changelog, Review effort 1/5

#615 Riemannian Updates In OptimizerJax
  mrmustard/lab/circuit_components.py
  mrmustard/lab/circuit_components_utils/b_to_ch.py
  mrmustard/lab/circuit_components_utils/b_to_ps.py
  mrmustard/lab/circuit_components_utils/b_to_q.py
  mrmustard/lab/circuits.py
  mrmustard/lab/states/dm.py
  mrmustard/lab/states/ket.py
  mrmustard/lab/states/vacuum.py
  mrmustard/math/backend_jax.py
  mrmustard/math/parameter_set.py
  mrmustard/math/parameters.py
  mrmustard/physics/ansatz/array_ansatz.py
  mrmustard/physics/ansatz/base.py
  mrmustard/physics/ansatz/polyexp_ansatz.py
  mrmustard/training/optimizer_jax.py
  mrmustard/training/parameter_update.py
  mrmustard/training/parameter_update_jax.py
  tests/test_lab/test_circuit_components.py
  tests/test_lab/test_circuit_components_utils/test_b_to_ch.py
  tests/test_lab/test_circuit_components_utils/test_b_to_ps.py
  tests/test_lab/test_circuit_components_utils/test_b_to_q.py
  tests/test_training/test_opt_lab_jax.py
Labels: enhancement, no changelog, Review effort 4/5

#632 feat: [sc-96057] Better README bagdes
  .github/workflows/upload.yml
  README.md
  pyproject.toml
Labels: no changelog

#616 added repr for parameter set
  .github/CHANGELOG.md
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/math/parameter_set.py
  mrmustard/math/parameters.py
  tests/test_math/test_backend_manager.py
  tests/test_math/test_parameter_set.py
  tests/test_math/test_parameters.py
Labels: enhancement, Review effort 2/5

#617 Complexify dgate
  mrmustard/lab/circuit_components.py
  mrmustard/lab/circuit_components_utils/trace_out.py
  mrmustard/lab/states/base.py
  mrmustard/lab/states/coherent.py
  mrmustard/lab/states/displaced_squeezed.py
  mrmustard/lab/states/dm.py
  mrmustard/lab/states/ket.py
  mrmustard/lab/transformations/amplifier.py
  mrmustard/lab/transformations/dgate.py
  mrmustard/lab/transformations/fockdamping.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/jax_vjps/fock_utils.py
  mrmustard/physics/triples.py
  mrmustard/training/optimizer.py
  mrmustard/training/parameter_update.py
  tests/test_lab/test_circuit_components.py
  tests/test_lab/test_circuit_components_utils/test_b_to_ps.py
  tests/test_lab/test_circuit_components_utils/test_b_to_q.py
  tests/test_lab/test_circuit_components_utils/test_trace_out.py
  tests/test_lab/test_circuits.py
  tests/test_lab/test_path/test_branch_and_bound.py
  tests/test_lab/test_samplers.py
  tests/test_lab/test_states/test_coherent.py
  tests/test_lab/test_states/test_displaced_squeezed.py
  tests/test_lab/test_states/test_dm.py
  tests/test_lab/test_states/test_ket.py
  tests/test_lab/test_states/test_quadrature_eigenstate.py
  tests/test_lab/test_states/test_states_visualization.py
  tests/test_lab/test_transformations/test_amplifier.py
  tests/test_lab/test_transformations/test_czgate.py
  tests/test_lab/test_transformations/test_dgate.py
  tests/test_lab/test_transformations/test_mzgate.py
  tests/test_lab/test_transformations/test_transformations_base.py
  tests/test_math/test_backend_manager.py
  tests/test_math/test_fast_diagonal.py
  tests/test_math/test_lattice/test_lattice_functions.py
  tests/test_physics/test_bargmann_utils.py
  tests/test_physics/test_fidelity.py
  tests/test_physics/test_fock_utils.py
  tests/test_physics/test_gaussian_integrals.py
  tests/test_physics/test_symplectics.py
  tests/test_physics/test_triples.py
  tests/test_physics/test_wigner.py
  tests/test_training/test_optimizer.py
  tests/test_utils/test_serialize.py
Labels: enhancement, no changelog, tests, Review effort 5/5
