Repository XanaduAI/MrMustard, pull requests merged in 2025-08, with the labels that each got.

#639 Bugfix: DM.expectation Fock shape lookahead
  .github/CHANGELOG.md
  mrmustard/lab/circuit_components.py
  mrmustard/lab/states/dm.py
  tests/test_lab/test_states/test_dm.py
Labels: Bug fix, Review effort 3/5

#638 add seed keyword on random methods, plus tests
  .github/CHANGELOG.md
  mrmustard/lab/states/dm.py
  mrmustard/lab/states/ket.py
  mrmustard/lab/transformations/base.py
  mrmustard/math/backend_manager.py
  tests/test_lab/test_states/test_dm.py
  tests/test_lab/test_states/test_ket.py
  tests/test_lab/test_transformations/test_transformations_base.py
Labels: enhancement, Review effort 3/5

#643 Making `CircuitComponent.fock_array` more memory efficient for scalar c
  .github/CHANGELOG.md
  mrmustard/lab/circuit_components.py
Labels: enhancement, Review effort 2/5

#642 2chip gbs
  .github/CHANGELOG.md
  mrmustard/math/backend_manager.py
  mrmustard/math/jax_vjps/hermite.py
  mrmustard/training/parameter_update.py
Labels: enhancement, Review effort 2/5
