Repository XanaduAI/MrMustard, pull requests merged in 2025-06, with the labels that each got.

#599 Adding persistent compilation cache to BackendJax
  .github/workflows/tests_jax.yml
  .gitignore
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  pyproject.toml
  tests/conftest.py
  uv.lock
Labels: no changelog

#598 Adding support for `optimize` in einsum
  mrmustard/lab/states/dm.py
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/utils/settings.py
Labels: no changelog

#595 Add `out` keyword to hermite_renormalized
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  mrmustard/math/lattice/strategies/vanilla/batch.py
  mrmustard/math/lattice/strategies/vanilla/core.py
  mrmustard/math/lattice/strategies/vanilla/gradients.py
  mrmustard/physics/representations.py
  tests/test_math/test_lattice/test_lattice_functions.py
  tests/test_math/test_lattice/test_vanilla.py
Labels: no changelog

#611 Backend argument in math.einsum
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_manager.py
  mrmustard/math/backend_numpy.py
  mrmustard/math/backend_tensorflow.py
  tests/test_math/test_backend_manager.py
Labels: enhancement, no changelog, Review effort 3/5

#600 Changed np.array --> np.asarray to reduce memory overhead
  .github/CHANGELOG.md
  mrmustard/math/backend_jax.py
  mrmustard/math/backend_numpy.py
Labels: enhancement, Review effort 2/5
